
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 19 13:19:32 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 39;
  public static final int POR = 31;
  public static final int PUNTOYCOMA = 47;
  public static final int PCIERRE = 42;
  public static final int LIT_REAL = 27;
  public static final int INT = 21;
  public static final int REFERENCIA = 51;
  public static final int LIT_CADENA = 28;
  public static final int DELETE = 8;
  public static final int WRITE = 6;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int IGUAL = 38;
  public static final int TYPE = 16;
  public static final int EVAL = 17;
  public static final int OR = 19;
  public static final int BOOL = 23;
  public static final int CALL = 9;
  public static final int DIV = 32;
  public static final int MAYIGUAL = 37;
  public static final int IF = 2;
  public static final int LLAVECIERRE = 46;
  public static final int EOF = 0;
  public static final int TRUE = 11;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int CORAP = 43;
  public static final int LIT_ENT = 26;
  public static final int MENOS = 30;
  public static final int NULL = 13;
  public static final int MENOR = 34;
  public static final int MOD = 33;
  public static final int PUNTERO = 50;
  public static final int ASIGNACION = 40;
  public static final int MAYOR = 35;
  public static final int REAL = 22;
  public static final int PAP = 41;
  public static final int ELSE = 3;
  public static final int PUNTO = 49;
  public static final int FINDECL = 52;
  public static final int NL = 10;
  public static final int READ = 5;
  public static final int IDEN = 25;
  public static final int WHILE = 4;
  public static final int MENIGUAL = 36;
  public static final int PROC = 15;
  public static final int STRING = 24;
  public static final int CORCIERRE = 44;
  public static final int LLAVEAP = 45;
  public static final int FALSE = 12;
  public static final int STRUCT = 14;
  public static final int MAS = 29;
}

