
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 24 18:47:13 CET 2025
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 49;
  public static final int POR = 42;
  public static final int PUNTOYCOMA = 25;
  public static final int PCIERRE = 21;
  public static final int LIT_REAL = 32;
  public static final int INT = 16;
  public static final int REFERENCIA = 28;
  public static final int LIT_CADENA = 33;
  public static final int DELETE = 8;
  public static final int WRITE = 6;
  public static final int NOT = 40;
  public static final int AND = 38;
  public static final int IGUAL = 48;
  public static final int TYPE = 14;
  public static final int OR = 39;
  public static final int EVAL = 15;
  public static final int BOOL = 18;
  public static final int CALL = 9;
  public static final int DIV = 41;
  public static final int MAYIGUAL = 47;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 24;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int CORAP = 50;
  public static final int COMA = 26;
  public static final int LIT_ENT = 31;
  public static final int MENOS = 37;
  public static final int MENOR = 44;
  public static final int NULL = 11;
  public static final int MOD = 43;
  public static final int LIT_BOOLEANO = 34;
  public static final int PUNTERO = 51;
  public static final int ASIGNACION = 35;
  public static final int MAYOR = 45;
  public static final int REAL = 17;
  public static final int PAP = 20;
  public static final int ELSE = 3;
  public static final int PUNTO = 27;
  public static final int NL = 10;
  public static final int FINDECL = 29;
  public static final int READ = 5;
  public static final int IDEN = 30;
  public static final int WHILE = 4;
  public static final int MENIGUAL = 46;
  public static final int PROC = 13;
  public static final int STRING = 19;
  public static final int CORCIERRE = 22;
  public static final int LLAVEAP = 23;
  public static final int STRUCT = 12;
  public static final int MAS = 36;
}

