
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 22 15:29:02 CET 2025
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 33;
  public static final int POR = 25;
  public static final int PUNTOYCOMA = 41;
  public static final int PCIERRE = 36;
  public static final int LIT_REAL = 49;
  public static final int INT = 19;
  public static final int LIT_CADENA = 50;
  public static final int REFERENCIA = 45;
  public static final int DELETE = 8;
  public static final int WRITE = 6;
  public static final int NOT = 18;
  public static final int AND = 16;
  public static final int IGUAL = 32;
  public static final int TYPE = 14;
  public static final int EVAL = 15;
  public static final int OR = 17;
  public static final int BOOL = 21;
  public static final int CALL = 9;
  public static final int DIV = 26;
  public static final int MAYIGUAL = 31;
  public static final int IF = 2;
  public static final int LLAVECIERRE = 40;
  public static final int EOF = 0;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int LIT_ENT = 48;
  public static final int COMA = 42;
  public static final int CORAP = 37;
  public static final int MENOS = 24;
  public static final int NULL = 11;
  public static final int MENOR = 28;
  public static final int MOD = 27;
  public static final int LIT_BOOLEANO = 51;
  public static final int PUNTERO = 44;
  public static final int ASIGNACION = 34;
  public static final int REAL = 20;
  public static final int MAYOR = 29;
  public static final int PAP = 35;
  public static final int ELSE = 3;
  public static final int PUNTO = 43;
  public static final int FINDECL = 46;
  public static final int NL = 10;
  public static final int READ = 5;
  public static final int IDEN = 47;
  public static final int WHILE = 4;
  public static final int MENIGUAL = 30;
  public static final int PROC = 13;
  public static final int STRING = 22;
  public static final int CORCIERRE = 38;
  public static final int LLAVEAP = 39;
  public static final int STRUCT = 12;
  public static final int MAS = 23;
}

