
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 24 20:49:29 CET 2025
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 48;
  public static final int POR = 41;
  public static final int PUNTOYCOMA = 24;
  public static final int PCIERRE = 20;
  public static final int LIT_REAL = 31;
  public static final int INT = 15;
  public static final int REFERENCIA = 27;
  public static final int LIT_CADENA = 32;
  public static final int DELETE = 8;
  public static final int WRITE = 6;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int IGUAL = 47;
  public static final int TYPE = 13;
  public static final int OR = 38;
  public static final int EVAL = 14;
  public static final int BOOL = 17;
  public static final int CALL = 9;
  public static final int DIV = 40;
  public static final int MAYIGUAL = 46;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 23;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int CORAP = 49;
  public static final int COMA = 25;
  public static final int LIT_ENT = 30;
  public static final int MENOS = 36;
  public static final int NULL = 51;
  public static final int MENOR = 43;
  public static final int MOD = 42;
  public static final int LIT_BOOLEANO = 33;
  public static final int PUNTERO = 50;
  public static final int ASIGNACION = 34;
  public static final int MAYOR = 44;
  public static final int REAL = 16;
  public static final int PAP = 19;
  public static final int ELSE = 3;
  public static final int PUNTO = 26;
  public static final int NL = 10;
  public static final int FINDECL = 28;
  public static final int READ = 5;
  public static final int IDEN = 29;
  public static final int WHILE = 4;
  public static final int MENIGUAL = 45;
  public static final int PROC = 12;
  public static final int STRING = 18;
  public static final int CORCIERRE = 21;
  public static final int LLAVEAP = 22;
  public static final int STRUCT = 11;
  public static final int MAS = 35;
}

