/* Generated By:JavaCC: Do not edit this line. ConstructorASTsTinyConstants.java */
package c_ast_descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTsTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int ELSE = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int READ = 4;
  /** RegularExpression Id. */
  int WRITE = 5;
  /** RegularExpression Id. */
  int NEW = 6;
  /** RegularExpression Id. */
  int DELETE = 7;
  /** RegularExpression Id. */
  int CALL = 8;
  /** RegularExpression Id. */
  int NL = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int STRUCT = 13;
  /** RegularExpression Id. */
  int PROC = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int EVAL = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int REAL = 21;
  /** RegularExpression Id. */
  int BOOL = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int IDEN = 24;
  /** RegularExpression Id. */
  int LIT_ENT = 25;
  /** RegularExpression Id. */
  int LIT_REAL = 26;
  /** RegularExpression Id. */
  int LIT_CADENA = 27;
  /** RegularExpression Id. */
  int LETRA = 28;
  /** RegularExpression Id. */
  int DIGITO_POSITIVO = 29;
  /** RegularExpression Id. */
  int DIGITO = 30;
  /** RegularExpression Id. */
  int PARTE_ENTERA = 31;
  /** RegularExpression Id. */
  int PARTE_DECIMAL = 32;
  /** RegularExpression Id. */
  int EXPONENTE = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IF>",
    "<ELSE>",
    "<WHILE>",
    "<READ>",
    "<WRITE>",
    "<NEW>",
    "<DELETE>",
    "<CALL>",
    "<NL>",
    "<TRUE>",
    "<FALSE>",
    "<NULL>",
    "<STRUCT>",
    "<PROC>",
    "<TYPE>",
    "\"@\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<INT>",
    "<REAL>",
    "<BOOL>",
    "<STRING>",
    "<IDEN>",
    "<LIT_ENT>",
    "<LIT_REAL>",
    "<LIT_CADENA>",
    "<LETRA>",
    "<DIGITO_POSITIVO>",
    "<DIGITO>",
    "<PARTE_ENTERA>",
    "<PARTE_DECIMAL>",
    "<EXPONENTE>",
    "<token of kind 34>",
    "<token of kind 35>",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\",\"",
    "\"&\"",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\".\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
  };

}
